# Generated by Django 3.2.8 on 2021-11-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
